<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="KALAMSIR-PC" ignored="0" name="Default test" tests="4" failures="2" timestamp="2021-06-21T08:31:34 IST" time="2.599" errors="0">
  <testcase name="runScenario" time="2.145" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="2.145" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="2.148" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at gluecode.StepdefForFeature2.method10(StepdefForFeature2.java:71)
at ✽.status code is "400" as per "wrong" and content type is "application/json"(file:///E:/apibatch4/org.magnitia.5bdd-ra-cucumber-pico-testng/src/test/resources/features/feature2.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="2.151" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at gluecode.StepdefForFeature2.method10(StepdefForFeature2.java:71)
at ✽.status code is "200" as per "duplicate" and content type is "application/json"(file:///E:/apibatch4/org.magnitia.5bdd-ra-cucumber-pico-testng/src/test/resources/features/feature2.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
